name: weight_predict
channels:
  - conda-forge
dependencies:
  - python=3.8.5
  - jupyter=1.0.0
  - matplotlib=3.3.1
  - pandas=1.4.0
  - joblib=1.1.0
  - numpy=1.22.2
  - scipy=1.8.0
  - scikit-learn=1.0.2